# Generated by Django 3.2 on 2024-10-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20241020_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, help_text='Введите код подтверждения из письма', max_length=150, verbose_name='Код подтверждения'),
        ),
    ]
